x-srht-service: &srht-service
  configs:
    - source: main
      target: /etc/sr.ht/config.ini
    - source: pgp-pubkey
      target: /etc/sr.ht/pgp/pubkey.asc
    - source: pgp-privkey
      target: /etc/sr.ht/pgp/privkey.asc

name: srht

configs:
  main:
    file: config.ini
  pgp-pubkey:
    file: pgp/pubkey.asc
  pgp-privkey:
    file: pgp/privkey.asc
  git-sshd:
    file: git-sshd/sshd_config
  git-sshd-rsa-pubkey:
    file: git-sshd/ssh_host_rsa_key.pub
  git-sshd-rsa-privkey:
    file: git-sshd/ssh_host_rsa_key
  git-sshd-ed25519-pubkey:
    file: git-sshd/ssh_host_ed25519_key.pub
  git-sshd-ed25519-privkey:
    file: git-sshd/ssh_host_ed25519_key

volumes:
  postgres-data:
  minio-data:
  git-repos:

services:
  redis:
    image: "redis:7.2.4-alpine"
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./init-postgres.sh:/docker-entrypoint-initdb.d/init.sh"
      - "./meta.sr.ht/schema.sql:/data/meta.sr.ht.sql"
      - "./todo.sr.ht/schema.sql:/data/todo.sr.ht.sql"
      - "./git.sr.ht/schema.sql:/data/git.sr.ht.sql"
      - "./man.sr.ht/schema.sql:/data/man.sr.ht.sql"
      - "./paste.sr.ht/schema.sql:/data/paste.sr.ht.sql"
      - "./hub.sr.ht/schema.sql:/data/hub.sr.ht.sql"
  minio:
    image: "quay.io/minio/minio"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: jIPk1RZ8gdhQwnUL4YtrOAXsFpHvb4Mw8hEwfLq
    volumes:
      - "minio-data:/data"
    ports:
      - "127.0.0.1:9001:9001"
    command: server --console-address ":9001" /data
  meta-api:
    <<: *srht-service
    build:
      target: srht-meta
    develop:
      watch:
        - path: meta.sr.ht/api
          action: rebuild
    depends_on:
      - redis
      - postgres
    ports:
      - "127.0.0.1:5100:5100"
    command: /src/meta.sr.ht/api/api
  meta:
    <<: *srht-service
    build:
      target: srht-meta
    develop:
      watch:
        - path: meta.sr.ht/metasrht
          action: sync
          target: /src/meta.sr.ht/metasrht
    depends_on:
      - redis
      - postgres
      - meta-api
    ports:
      - "127.0.0.1:5000:5000"
    command: flask --app metasrht.app:app --debug run --host=0.0.0.0 --port=5000
  todo-api:
    <<: *srht-service
    build:
      target: srht-todo
    depends_on:
      - redis
      - postgres
    develop:
      watch:
        - path: todo.sr.ht/api
          action: rebuild
    ports:
      - "127.0.0.1:5103:5103"
    command: /src/todo.sr.ht/api/api
  todo:
    <<: *srht-service
    build:
      target: srht-todo
    develop:
      watch:
        - path: todo.sr.ht/todosrht
          action: sync
          target: /src/todo.sr.ht/todosrht
    depends_on:
      - redis
      - postgres
      - todo-api
      - meta
    ports:
      - "127.0.0.1:5003:5003"
    command: flask --app todosrht.app:app --debug run --host=0.0.0.0 --port=5003
  todo-smtp:
    <<: *srht-service
    build:
      target: srht-todo
    develop:
      watch:
        - path: todo.sr.ht/todosrht-lmtp
          action: rebuild
        - path: todo.sr.ht/todosrht
          action: rebuild
    depends_on:
      - redis
      - postgres
      - todo-api
    ports:
      - "127.0.0.1:5903:5903"
    command: /src/todo.sr.ht/todosrht-lmtp
  git-api:
    <<: *srht-service
    build:
      target: srht-git
    user: git
    depends_on:
      - redis
      - postgres
      - minio
    volumes:
      - "git-repos:/var/lib/git"
    develop:
      watch:
        - path: git.sr.ht/api
          action: rebuild
    ports:
      - "127.0.0.1:5101:5101"
    command: /src/git.sr.ht/api/api
  git:
    <<: *srht-service
    build:
      target: srht-git
    user: git
    volumes:
      - "git-repos:/var/lib/git"
    develop:
      watch:
        - path: git.sr.ht/gitsrht
          action: sync
          target: /src/git.sr.ht/gitsrht
        - path: scm.sr.ht/scmsrht
          action: sync
          target: /src/scm.sr.ht/scmsrht
    depends_on:
      - redis
      - postgres
      - minio
      - git-api
      - meta
    ports:
      - "127.0.0.1:5001:5001"
    command: flask --app gitsrht.app:app --debug run --host=0.0.0.0 --port=5001
  git-ssh:
    build:
      target: srht-git
    volumes:
      - "git-repos:/var/lib/git"
    configs:
      - source: main
        target: /etc/sr.ht/config.ini
      - source: git-sshd
        target: /etc/ssh/sshd_config
      - source: git-sshd-rsa-pubkey
        target: /etc/ssh/ssh_host_rsa_key.pub
      - source: git-sshd-rsa-privkey
        target: /etc/ssh/ssh_host_rsa_key
      - source: git-sshd-ed25519-pubkey
        target: /etc/ssh/ssh_host_ed25519_key.pub
      - source: git-sshd-ed25519-privkey
        target: /etc/ssh/ssh_host_ed25519_key
    develop:
      watch:
        - path: git.sr.ht # TODO: narrow down scope
          action: rebuild
    ports:
      - "127.0.0.1:5901:22"
    command: /usr/sbin/sshd -D -e
  man-api:
    <<: *srht-service
    build:
      target: srht-man
    depends_on:
      - redis
      - postgres
      - git
    develop:
      watch:
        - path: man.sr.ht/api
          action: rebuild
    ports:
      - "127.0.0.1:5104:5104"
    command: /src/man.sr.ht/api/api
  man:
    <<: *srht-service
    build:
      target: srht-man
    develop:
      watch:
        - path: man.sr.ht/mansrht
          action: sync
          target: /src/man.sr.ht/mansrht
    depends_on:
      - redis
      - postgres
      - man-api
      - meta
    ports:
      - "127.0.0.1:5004:5004"
    command: flask --app mansrht.app:app --debug run --host=0.0.0.0 --port=5004
  paste-api:
    <<: *srht-service
    build:
      target: srht-paste
    depends_on:
      - redis
      - postgres
    develop:
      watch:
        - path: paste.sr.ht/api
          action: rebuild
    ports:
      - "127.0.0.1:5111:5111"
    command: /src/paste.sr.ht/api/api
  paste:
    <<: *srht-service
    build:
      target: srht-paste
    develop:
      watch:
        - path: paste.sr.ht/pastesrht
          action: sync
          target: /src/paste.sr.ht/pastesrht
    depends_on:
      - redis
      - postgres
      - paste-api
      - meta
    ports:
      - "127.0.0.1:5011:5011"
    command: flask --app pastesrht.app:app --debug run --host=0.0.0.0 --port=5011
  hub-api:
    <<: *srht-service
    build:
      target: srht-hub
    depends_on:
      - redis
      - postgres
    develop:
      watch:
        - path: hub.sr.ht/api
          action: rebuild
    ports:
      - "127.0.0.1:5112:5112"
    command: /src/hub.sr.ht/api/api
  hub:
    <<: *srht-service
    build:
      target: srht-hub
    develop:
      watch:
        - path: hub.sr.ht/hubsrht
          action: sync
          target: /src/hub.sr.ht/hubsrht
    depends_on:
      - redis
      - postgres
      - hub-api
      - meta
    ports:
      - "127.0.0.1:5012:5012"
    command: flask --app hubsrht.app:app --debug run --host=0.0.0.0 --port=5012
